### ISSUE TITLE
Error when training model in NWPU VHR dataset

### ISSUE THREAD

**Issue by TerrafYassin** [ZhAnGToNG1/MSFC-Net#4]

**Comment by TerrafYassin** [comment]
Error when start training model in NWPU  VHR dataset

==> initializing NWPU train data.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loaded train 260 samples
Starting training...
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    main(opt)
  File "train.py", line 76, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/content/drive/MyDrive/MSFC-Net/src/lib/trains/base_trainer.py", line 117, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/content/drive/MyDrive/MSFC-Net/src/lib/trains/base_trainer.py", line 56, in run_epoch
    for iter_id , batches in enumerate(data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/MSFC-Net/src/lib/datasets/sample/ctdet_multiscale.py", line 79, in __getitem__
    ret3 = self.gt_transform(c, s, input_w, input_h, self.num_classes, num_objs, anns, 2, 2, flipped, width, inp ,thresh= 1)
  File "/content/drive/MyDrive/MSFC-Net/src/lib/datasets/sample/ctdet_multiscale.py", line 111, in gt_transform
    cls_id = int(self.cat_ids[ann['category_id']])
KeyError: 10

**Comment by ZhAnGToNG1** [comment]
Please check https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/lib/datasets/dataset/DOTA.py#L28.
https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/lib/datasets/dataset/DOTA.py#L25
https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/dota_dekit/DOTA2COCO.py#L7. Whether these parameters about categories have been changed according your dataset.

**Comment by TerrafYassin** [comment]
Thank you
